refactor: 💡 modular file architecture (first pass) (#832)
* chore: 🤖 update required packages

* chore: 🤖 provide styled components types

* fix: 🐛 linter should ignore d.ts files

* fix: 🐛 use double quotes

* fix: 🐛 vite > v2 separates vitest config

* chore: 🤖 reorder package

* chore: 🤖 remove side property (deprecated)

* fix: 🐛 dropdown amends

* fix: 🐛 theme prop

* fix: 🐛 type

* chore: 🤖 TIAS build version supported on next v16 RSC

* chore: 🤖 WIP ongoing styled-component v6.1.11 (non experimental) support

* chore: 🤖 strict react version for dev

* fix: 🐛 missing ref on forwardRef, might have plenty of these

* chore: 🤖 update lockfile

* chore: 🤖 remove optional flag from ref (typo)

* chore: 🤖 add comment for future ref

* refactor: 💡 banner

* chore: 🤖 lint amends (double quotes)

* refactor: 💡 removes style prop as typed prop

* chore: 🤖 remove ajv

* chore: 🤖 format

* test: 💍 add aria pressed to ButtonGroup

* chore: 🤖 format

* test: 💍 use local getByText

* chore: 🤖 update lockfile

* chore: 🤖 add changeset

* chore: 🤖 small text amend to trigger vercel deploy

* chore: 🤖 prevent running on CI

* chore: 🤖 add HUSKY to preven husky runnig pre-commit hook

* fix: 🐛 conflict resolution

* chore: 🤖 bump rc number

* docs: 📝 build esm, how to use

* chore: 🤖 ESM vite builder (wip)

* fix: 🐛 remove .tsx extension from import statements

* fix: 🐛 remove .tsx extension from import statements

* fix: 🐛 remove .tsx extension from import statements

* fix: 🐛 remove .ts extension from import statements

* fix: 🐛 remove .ts extension from import statements

* chore: 🤖 add eslint to assess import extensions not required

* chore: 🤖 format

* chore: 🤖 temporary custom resolve tsconfig path

* refactor: 💡 export from correct theme boundary

* chore: 🤖 node externals in vite, remove alias

* chore: 🤖 use relative paths

* chore: 🤖 use externalize deps

* chore: 🤖 for ESM compatibility, tweak/handle CJS components

* chore: revert ts alias rewrite to relative

* chore: lint do not allow barrel imports

* chore: remove excludes from tsconfig

* chore: set vite settings to preserve file struct in output

* fix: solve import cycles

* fix: solve import cycles in stories

* fix: build amends

* fix: add .js extension

* chore: analyze and visualise bundle

* chore: split ESM, CJS distribution

* chore: format

* fix: 🐛 lint code block

* fix: 🐛 import Separator

* chore: format

* fix: 🐛 import Separator

* chore: 🤖 add changeset

* chore: 🤖 use 0.0.251-rc.62

* chore: 🤖 resolve conflict resolution, deleted files which were removed in main branch

* chore: 🤖 resolve conflict resolution, middle truncator

* chore: 🤖 resolve conflict resolution, missing container changes

* refactor: 💡 FileMultiUpload to follow FileUpload due to middle truncator

* fix: 🐛 prevent icon success pushed right

* fix: 🐛 remove file size from multiple file upload

* chore: 🤖 merge conflict amend for ButtonGroup

* chore: 🤖 remove comment

* refactor: 💡 reduce import path redundancy (WIP, pt1)

* refactor: 💡 accordion as index

* refactor: 💡 rename component by directory name to index

* refactor: 💡 update import statements to prefer index

* chore: 🤖 remove old indexes (this was a failed attempt, which imported the reduntant name)

* fix: 🐛 import statements

* fix: 🐛 import statements

* fix: 🐛 import statements

* fix: 🐛 icon names in types

* chore: 🤖 add note

* chore: 🤖 format

* fix: 🐛 icon names location

* fix: 🐛 icon names location

* chore: 🤖 update changeset

* refactor: 💡 use component level barrel, to allow devs see component name on editor

* fix: 🐛 import statements

* chore: 🤖 add eslint to prevent imports from index and request use of leafs when possible

* fix: 🐛 dayjs version

* fix: 🐛 merge from main,m incorrectly changed

* chore: 🤖 prepare merge main

* fix: 🐛 merge conflicts

* refactor: 💡 further paths pass

* chore: 🤖 add note

* chore: 🤖 format

* refactor: 💡 further paths pass for AutoComplete

* fix: 🐛 merge conflict

* refactor: 💡 further paths pass for Collapsible

* chore: 🤖 init changeset

* fix: 🐛 merge conflict

* fix: 🐛 file extension

* fix: 🐛 file extension

* refactor: 💡 init GenericMenu structure

* chore: 🤖 add generic menu test

* chore: 🤖 add generic menu story

* refactor: 💡 make components/Common to avoid loose files

* refactor: 💡 move types

* refactor: 💡 update path changes for common components

* refactor: 💡 add Text index/exports

* refactor: 💡 first pass, move types to *.types.ts

* refactor: 💡 second pass, move types to *.types.ts

* refactor: 💡 third pass, move types to *.types.ts

* refactor: 💡 forth pass, move types to *.types.ts

* refactor: 💡 fifth pass, move types to *.types.ts

* refactor: 💡 export size color

* refactor: 💡 move types for Avatar

* fix: 🐛 imports

* fix: 🐛 types

* fix: 🐛 linter

* fix: 🐛 test

* chore: 🤖 add hmr benchmark

* chore: 🤖 make component build name index to remove redundancy

* chore: 🤖 generate exports, e.g. expose direct component imports and its types

chore: 🤖 generate exports, e.g. expose direct component imports and its types

* perf: ⚡ benchmark hmr deep nested components

* chore: 🤖 link @clickhouse/click-ui to itself, required for benchmark

* perf: ⚡ generate component exports, e.g. speedy component and type access

* refactor: 💡 remove unused re-export files

* chore: 🤖 update changeset

* chore: 🤖 remove comments

* chore: 🤖 merge conflict

* fix: 🐛 resole theme conflicts

* fix: 🐛 resolve theme types

* refactor: 💡 theme

* fix: 🐛 resolve merge conflicts due to circular deps

* refactor: 💡 theme

* refactor: 💡 remove hard typed theme

* fix: 🐛 types deps

* test: 💍 update test (due to merge issues)

* chore: 🤖 the asset system has to be updated to reflect architecture decisions, since its automated, here done manual changes

* fix: 🐛  error TS2724: './IconButton' has no exported member named 'IconButtonSize'.

* chore: 🤖 add TODO

* chore: 🤖 resolve merge conflict missing type

* chore: 🤖 remove deprecated

* fix: 🐛 ContextMenu.types.ts: Added type?: 'default' | 'danger' to the exported ContextMenuItemProps interface and remove duplicate

* refactor: 💡 move local type

* refactor: 💡 move local type (missed track file)

* refactor: 💡 changeset

* refactor: 💡 move ContextMenu types

* chore: 🤖 remove FlyoutHeaderProps and FlyoutFooterProps are each declared twice in the same file

* refactor: 💡 Replaced stale types in Flyout.types.ts with the correct definitions from Flyout.tsx

* fix: 🐛 typo, should be orientation

* refactor: 💡 changeset